README.md, src/main/java/ru/rt/restream/reindexer/ReindexerConfiguration.java, src/test/java/ru/rt/restream/reindexer/annotations/JsonTest.java, src/test/java/ru/rt/restream/reindexer/connector/BuiltinAggregationTest.java, src/test/java/ru/rt/restream/reindexer/connector/BuiltinJoinTest.java, src/test/java/ru/rt/restream/reindexer/connector/BuiltinMergeTest.java, src/test/java/ru/rt/restream/reindexer/connector/BuiltinReindexerTest.java, src/test/java/ru/rt/restream/reindexer/connector/CprotoAggregationTest.java, src/test/java/ru/rt/restream/reindexer/connector/CprotoJoinTest.java, src/test/java/ru/rt/restream/reindexer/connector/CprotoMergeTest.java, src/test/java/ru/rt/restream/reindexer/connector/CprotoReindexerTest.java
WINKDEV-8610: Переименовать Configuration в ReindexerConfiguration
=> RX-74 Rename Configuration class

src/main/java/ru/rt/restream/reindexer/Reindexer.java
=> Fix NPE in execSql

src/main/java/ru/rt/restream/reindexer/Query.java, src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
=> Fix 'is NULL' condition

src/main/java/ru/rt/restream/reindexer/Query.java, src/main/java/ru/rt/restream/reindexer/QueryLogBuilder.java, src/main/java/ru/rt/restream/reindexer/QueryResultIterator.java, src/main/java/ru/rt/restream/reindexer/Reindexer.java, src/test/java/ru/rt/restream/reindexer/connector/CprotoReindexerTest.java, src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
- Added a new method to the Query API: select(fields) that selects only the specified fields
- Added an overloaded execute(itemClass) method that accepts an item class
Closes gh-62
=> Allow Query for specific fields

src/main/java/ru/rt/restream/reindexer/Query.java, src/main/java/ru/rt/restream/reindexer/QueryLogBuilder.java, src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
=> Add Query.like

src/main/java/ru/rt/restream/reindexer/ReindexerConfiguration.java, src/main/java/ru/rt/restream/reindexer/binding/builtin/Builtin.java, src/main/java/ru/rt/restream/reindexer/binding/builtin/server/BuiltinServer.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/ConnectionPool.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/Cproto.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/DataSource.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/DataSourceFactory.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/DataSourceFactoryStrategy.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/PhysicalDataSource.java
=> Add support for multiple data sources

src/main/java/ru/rt/restream/reindexer/Query.java, src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
=> Add Query.isNotNull

src/main/java/ru/rt/restream/reindexer/ReindexerConfiguration.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/ConnectionPool.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/Cproto.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/DataSourceConfiguration.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/DataSourceFactory.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/DataSourceFactoryStrategy.java, src/main/java/ru/rt/restream/reindexer/binding/definition/Nodes.java
=> Add support of Synchronized, WriteReq, ReadOnly, PrefferRead strategies

src/main/java/ru/rt/restream/reindexer/Query.java, src/main/java/ru/rt/restream/reindexer/Reindexer.java, src/main/java/ru/rt/restream/reindexer/ReindexerNamespace.java
=> Fix StateInvalidatedException when stateToken is outdated

src/main/java/ru/rt/restream/reindexer/Namespace.java, src/main/java/ru/rt/restream/reindexer/ReindexerNamespace.java, src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
=> Add Namespace.execSql, Namespace.updateSql

src/main/java/ru/rt/restream/reindexer/ReindexerConfiguration.java, src/main/java/ru/rt/restream/reindexer/binding/definition/Nodes.java
- Add requireNonNull check for ReindexerConfiguration.dataSourceFactory
- Add Nodes.Node.syncState
- Rename Nodes.Node.pendedUpdatesCount to pendingUpdatesCount
=> Polish replication

src/main/java/ru/rt/restream/reindexer/Query.java, src/main/java/ru/rt/restream/reindexer/QueryLogBuilder.java, src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
=> Add Query.whereBetweenFields

src/main/java/ru/rt/restream/reindexer/annotations/ReindexAnnotationScanner.java, src/test/java/ru/rt/restream/reindexer/annotations/ReindexTest.java
=> Add quantity and uniq checks of indexes to ReindexerAnnotationScanner

src/main/java/ru/rt/restream/reindexer/binding/cproto/PhysicalConnection.java
=> Fix crash of tests with reindexer 4.20

pom.xml, src/test/java/ru/rt/restream/category/BuiltinTest.java, src/test/java/ru/rt/restream/category/CprotoTest.java, src/test/java/ru/rt/restream/reindexer/annotations/FullTextTest.java, src/test/java/ru/rt/restream/reindexer/annotations/JsonTest.java, src/test/java/ru/rt/restream/reindexer/annotations/ReindexTest.java, src/test/java/ru/rt/restream/reindexer/connector/BuiltinJoinTest.java, src/test/java/ru/rt/restream/reindexer/connector/BuiltinMergeTest.java, src/test/java/ru/rt/restream/reindexer/connector/BuiltinReindexerTest.java, src/test/java/ru/rt/restream/reindexer/connector/CprotoAggregationTest.java, src/test/java/ru/rt/restream/reindexer/connector/CprotoJoinTest.java, src/test/java/ru/rt/restream/reindexer/connector/CprotoMergeTest.java, src/test/java/ru/rt/restream/reindexer/connector/CprotoReindexerTest.java, src/test/java/ru/rt/restream/reindexer/db/DbBaseTest.java, src/test/java/ru/rt/restream/reindexer/db/DbLocator.java
=> Add support of cluster for tests

src/main/java/ru/rt/restream/reindexer/QueryLogBuilder.java
=> Fix query log for search by composite index

src/main/java/ru/rt/restream/reindexer/Namespace.java, src/main/java/ru/rt/restream/reindexer/Query.java, src/main/java/ru/rt/restream/reindexer/QueryLogBuilder.java, src/main/java/ru/rt/restream/reindexer/QueryResultIterator.java, src/main/java/ru/rt/restream/reindexer/QueryResultJsonIterator.java, src/main/java/ru/rt/restream/reindexer/ReindexerNamespace.java, src/main/java/ru/rt/restream/reindexer/ResultIterator.java, src/test/java/ru/rt/restream/reindexer/connector/AggregationTest.java, src/test/java/ru/rt/restream/reindexer/connector/JoinTest.java, src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
=> Add Query.reqTotal

src/main/java/ru/rt/restream/reindexer/Query.java, src/main/java/ru/rt/restream/reindexer/QueryResultIterator.java, src/main/java/ru/rt/restream/reindexer/binding/Consts.java, src/main/java/ru/rt/restream/reindexer/binding/QueryResult.java, src/main/java/ru/rt/restream/reindexer/binding/QueryResultReader.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/Cproto.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/CprotoRequestContext.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/CprotoTransactionContext.java
Add new params parsing for sharding support and remove item IDs request (those IDs were not used by connector anyway)
=> Add shard id parsing and remove item ids from request

.github/workflows/pr-build-workflow.yml, .github/workflows/release-build-workflow.yml, builtin-adapter/CMakeLists.txt, src/main/java/ru/rt/restream/reindexer/FieldType.java, src/main/java/ru/rt/restream/reindexer/Query.java, src/main/java/ru/rt/restream/reindexer/ReindexerIndex.java, src/main/java/ru/rt/restream/reindexer/annotations/Reindex.java, src/main/java/ru/rt/restream/reindexer/annotations/ReindexAnnotationScanner.java, src/main/java/ru/rt/restream/reindexer/binding/Consts.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/ByteBuffer.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/PhysicalConnection.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/cjson/CJsonItemWriter.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/cjson/CjsonElement.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/cjson/CjsonItemReader.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/cjson/CjsonPrimitive.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/cjson/encdec/CjsonDecoder.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/cjson/encdec/CjsonEncoder.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/cjson/encdec/Ctag.java, src/main/java/ru/rt/restream/reindexer/binding/definition/IndexDefinition.java, src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
=> GH-96 Add support of UUID indices

src/main/java/ru/rt/restream/reindexer/EnumType.java, src/main/java/ru/rt/restream/reindexer/annotations/Enumerated.java, src/main/java/ru/rt/restream/reindexer/annotations/ReindexAnnotationScanner.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/cjson/CJsonItemWriter.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/cjson/CjsonItemReader.java, src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
=> Consider supporting Enum type for index

src/main/java/ru/rt/restream/reindexer/ReindexerIndex.java, src/main/java/ru/rt/restream/reindexer/annotations/Reindex.java, src/main/java/ru/rt/restream/reindexer/annotations/ReindexAnnotationScanner.java, src/main/java/ru/rt/restream/reindexer/binding/definition/IndexDefinition.java, src/test/java/ru/rt/restream/reindexer/connector/CprotoReindexerTest.java, src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
=> Gh-110 add is_no_column

src/main/java/ru/rt/restream/reindexer/binding/Consts.java, src/main/java/ru/rt/restream/reindexer/binding/cproto/ByteBuffer.java, src/main/java/ru/rt/restream/reindexer/vector/params/BaseKnnSearchParam.java, src/main/java/ru/rt/restream/reindexer/vector/params/IndexBfSearchParam.java, src/main/java/ru/rt/restream/reindexer/vector/params/IndexHnswSearchParam.java, src/main/java/ru/rt/restream/reindexer/vector/params/IndexIvfSearchParam.java, src/main/java/ru/rt/restream/reindexer/vector/params/KnnParams.java, src/main/java/ru/rt/restream/reindexer/vector/params/KnnSearchParam.java, src/test/java/ru/rt/restream/reindexer/connector/FloatVectorBfTest.java, src/test/java/ru/rt/restream/reindexer/connector/FloatVectorHnswTest.java, src/test/java/ru/rt/restream/reindexer/connector/FloatVectorIvfTest.java
=> Gh-117 add parameter radius to knn search
